In [3]:
from hmm.continuous.GMHMM import GMHMM
from hmm.discrete.DiscreteHMM import DiscreteHMM
import numpy as np

Model attributes:
   - n            : number of hidden states
   - m            : number of mixtures in each state (each 'symbol' like in the discrete case points to a mixture)
   - d            : number of features (an observation can contain multiple features)
   - A            : hidden states transition probability matrix ([NxN] numpy array)
   - means        : means of the different mixtures ([NxMxD] numpy array)
   - covars       : covars of the different mixtures ([NxM] array of [DxD] covar matrices)
   - w            : weighing of each state's mixture components ([NxM] numpy array)
   - pi           : initial state's PMF ([N] numpy array).

In [4]:
N = 3 # number of hidden states
M = 2 # number of mixtures in each state
D = 8 # number of features (a observation can contain multiple features)

In [5]:
atmp = np.random.random_sample((N, N))
row_sums = atmp.sum(axis=1)
A = np.array(atmp / row_sums[:, np.newaxis], dtype=np.double)
print("Transition Matrix A [NxN]")
print(A)

Transition Matrix A [NxN]
[[3.69558536e-01 1.53840972e-01 4.76600492e-01]
 [2.72078465e-02 5.91028615e-01 3.81763539e-01]
 [3.57712387e-01 1.89778146e-04 6.42097835e-01]]


In [6]:
wtmp = np.random.random_sample((N, M))
row_sums = wtmp.sum(axis=1)
w = np.array(wtmp / row_sums[:, np.newaxis], dtype=np.double)
print("Weight of each state's mixture components [NxM]")
print(w)

Weight of each state's mixture components [NxM]
[[0.78552516 0.21447484]
 [0.76446394 0.23553606]
 [0.71334808 0.28665192]]


In [7]:
means = np.array((0.6 * np.random.random_sample((N, M, D)) - 0.3), dtype=np.double)
print("Means of the different mixtures [NxMxD]")
print(means.shape)

Means of the different mixtures [NxMxD]
(3, 2, 8)


In [8]:
covars = np.zeros((N,M,D,D))

for i in range(N):
    for j in range(M):
        for k in range(D):
            covars[i][j][k][k] = 1
print("Covars of the different mixtures ([NxM] array of [DxD] covar matrices)")            
print(covars.shape)

Covars of the different mixtures ([NxM] array of [DxD] covar matrices)
(3, 2, 8, 8)


In [9]:
pitmp = np.random.random_sample((N))
pi = np.array(pitmp / sum(pitmp), dtype=np.double)
print("initial state")
print(pi)

initial state
[0.2487938  0.32196163 0.42924457]


In [10]:
# initialization
gmmhmm = GMHMM(N, M, D, A, means, covars, w, pi, init_type='user', verbose=True)
print(gmmhmm)

In [11]:
# observation matrix
obs = np.array((0.6 * np.random.random_sample((40, D)) - 0.3), dtype=np.double)
print(obs)

[[-0.09841962 -0.15784341  0.11217874  0.01376459  0.1240452  -0.21902754
   0.1452936   0.23827656]
 [-0.17512072 -0.07495965 -0.09817191 -0.19794337  0.19823254  0.24071129
  -0.12361502 -0.29688125]
 [ 0.13684656  0.29833855 -0.27260784 -0.02288802 -0.17944799  0.07566956
   0.0757974   0.22623011]
 [-0.01299061  0.16196871 -0.08405203 -0.26419362  0.27204623  0.19745129
  -0.12451726  0.00787489]
 [-0.15781394 -0.08952472 -0.23419937  0.0670595  -0.10105293 -0.23548033
   0.25854063 -0.28844456]
 [-0.0096004  -0.27298445 -0.12829774 -0.21924423 -0.28086764 -0.28732014
   0.0910264  -0.03846733]
 [ 0.28712741  0.16662789 -0.14490986  0.22995602  0.25481249  0.06844751
   0.13060958 -0.26726214]
 [-0.14859886  0.00117187  0.15320016 -0.24017839 -0.2281971   0.15638371
   0.13916334  0.00173624]
 [ 0.27042021 -0.04702916 -0.2183786   0.10186285 -0.00494162 -0.20334151
  -0.065476   -0.21786019]
 [ 0.29416712 -0.01861745 -0.21349377 -0.05233317 -0.22805378  0.06277061
   0.25808693 -0.

In [12]:
print ("Doing Baum-welch")
gmmhmm.train(obs,1000)

Doing Baum-welch
1.4921706930656138e-133 1.3939250415359183e-132
5.495926132253086e-134 1.3939250415359183e-132
1.6860219067978251e-133 1.3939250415359183e-132
1.1661038320053848e-134 1.3939250415359183e-132
2.241223491028714e-133 1.3939250415359183e-132
1.4335437770963929e-133 1.3939250415359183e-132
2.4950298780663667e-133 1.3939250415359183e-132
1.1711744143267065e-136 1.3939250415359183e-132
3.923886498464096e-133 1.3939250415359183e-132
1.5351676441852224e-133 1.3939250415359183e-132
5.666915065585673e-134 1.3939250415359183e-132
2.0019518035887286e-133 1.3939250415359183e-132
8.104261518659745e-135 1.3939250415359183e-132
1.5610970548131722e-133 1.3939250415359183e-132
1.14984760866858e-133 1.3939250415359183e-132
2.5016326442094694e-133 1.3939250415359183e-132
1.1768954262435891e-136 1.3939250415359183e-132
4.540642642722603e-133 1.3939250415359183e-132
1.6406525895402301e-133 1.3939250415359183e-132
6.036885377523625e-134 1.3939250415359183e-132
1.8735017762886968e-133 1.393925

('iter: ', 1, ', L(model|O) =', 91.88113855820194, ', L(model_new|O) =', 122.74720154755815, ', converging =', True)
6.131635292606608e+48 2.0343810471051336e+53
7.977168847543819e+49 2.0343810471051336e+53
1.101812562229886e+49 2.0343810471051336e+53
2.0701478315515475e+50 2.0343810471051336e+53
1.9887518689839387e+53 2.0343810471051336e+53
4.175444065611159e+51 2.0343810471051336e+53
2.422215286563992e+49 2.0343810471051336e+53
4.199822682907801e+47 2.0343810471051336e+53
5.889537882892331e+49 2.0343810471051336e+53
9.9108829417178e+49 2.034381047105133e+53
5.401294479076788e+49 2.034381047105133e+53
8.424679710545537e+49 2.034381047105133e+53
3.9176356482701244e+51 2.034381047105133e+53
1.5765811269148134e+53 2.034381047105133e+53
3.737963022938609e+52 2.034381047105133e+53
1.9737229580806978e+51 2.034381047105133e+53
1.4335651895089327e+48 2.034381047105133e+53
2.2702010467921743e+51 2.034381047105133e+53
3.345646848276782e+51 2.034381047105134e+53
1.0898027782693204e+51 2.03438104

2.4940766583360523e+53 1.836874950544545e+58
2.6540681013487276e+55 1.836874950544545e+58
7.104689454049773e+57 1.836874950544545e+58
2.688813166255351e+51 1.836874950544545e+58
7.506861711288403e+57 1.836874950544545e+58
6.899562204478133e+57 1.8368749505445453e+58
3.8870989544424427e+55 1.8368749505445453e+58
2.268415283479343e+57 1.8368749505445453e+58
1.2976289163591022e+53 1.8368749505445453e+58
2.161531209349944e+53 1.8368749505445453e+58
4.413012161246704e+53 1.8368749505445453e+58
6.326968001943147e+57 1.8368749505445453e+58
5.291087492022922e+52 1.8368749505445453e+58
2.834092897896785e+57 1.8368749505445453e+58
5.572497896731006e+57 1.8368749505445448e+58
3.5023506069588467e+55 1.8368749505445448e+58
7.619138566512321e+57 1.8368749505445448e+58
2.3021884048386608e+54 1.8368749505445448e+58
4.278164720100248e+54 1.8368749505445448e+58
3.255970041534075e+55 1.8368749505445448e+58
1.7824780777210206e+57 1.8368749505445448e+58
1.6629498268402603e+52 1.8368749505445448e+58
3.32045

3.073905455350599e+58 4.708162117354872e+64
6.1655128256326505e+62 4.708162117354872e+64
6.5492924247037e+54 4.708162117354872e+64
1.787108508904949e+63 4.708162117354872e+64
2.906249968134676e+63 4.708162117354872e+64
1.0051943013558522e+59 4.708162117354872e+64
1.3076735576312949e+64 4.708162117354872e+64
6.0859171651055214e+56 4.708162117354872e+64
3.6460945748099895e+57 4.708162117354872e+64
7.555050649392829e+58 4.708162117354872e+64
3.9679737929943766e+63 4.708162117354872e+64
2.8258005096693326e+56 4.708162117354872e+64
2.713048122890375e+64 4.708162117354872e+64
7.69406531000599e+62 4.708162117354872e+64
7.835768655497656e+56 4.708162117354872e+64
6.1048170551433025e+63 4.708162117354872e+64
4.745819057432615e+56 4.708162117354872e+64
8.371856065934649e+55 4.708162117354872e+64
1.0388980429495952e+59 4.708162117354872e+64
3.0793677852836153e+63 4.708162117354872e+64
6.457180857705462e+54 4.708162117354872e+64
3.71279245639824e+64 4.708162117354872e+64
1.680795797293748e+63 4.70

4.482523087513771e+68 1.0176369703982339e+70
9.966122301974719e+55 1.0176369703982339e+70
4.850525284944742e+54 1.0176369703982339e+70
8.587347566942134e+57 1.0176369703982339e+70
4.975103609776188e+69 1.0176369703982339e+70
8.807822248688305e+56 1.0176369703982339e+70
1.4433834725288633e+69 1.0176369703982339e+70
8.266140792692199e+69 1.0176369703982338e+70
2.273589397972033e+61 1.0176369703982338e+70
1.8593107229203093e+67 1.0176369703982338e+70
2.4190004085896435e+57 1.0176369703982338e+70
3.033500678024915e+58 1.0176369703982338e+70
3.461584174003912e+57 1.0176369703982338e+70
1.8825651867912656e+69 1.0176369703982338e+70
8.587406656233062e+58 1.0176369703982338e+70
9.070594411688193e+66 1.0176369703982338e+70
6.406455475347701e+69 1.017636970398234e+70
1.0625995680570612e+60 1.017636970398234e+70
3.742250503075584e+69 1.017636970398234e+70
6.120315319150812e+58 1.017636970398234e+70
4.6283323575745324e+58 1.017636970398234e+70
2.2744616576295658e+61 1.017636970398234e+70
1.2288033

5.768310039998429e+68 2.1417064973324494e+75
2.2289321831247045e+69 2.1417064973324494e+75
5.135756848934923e+71 2.1417064973324494e+75
2.135375556262702e+75 2.1417064973324494e+75
1.448729485547403e+71 2.1417064973324494e+75
8.916951391279144e+57 2.1417064973324494e+75
5.669620358846998e+72 2.1417064973324494e+75
1.7303383019396997e+69 2.1417064973324494e+75
8.939098902381707e+54 2.1417064973324494e+75
1.4543785670105137e+71 2.1417064973324494e+75
5.547803010408121e+64 2.1417064973324494e+75
1.3628282831469476e+66 2.1417064973324494e+75
5.135742665871879e+71 2.1417064973324494e+75
5.646866511109162e+72 2.1417064973324494e+75
3.705519716227295e+58 2.1417064973324494e+75
2.1353988869414435e+75 2.1417064973324494e+75
3.690129265766276e+72 2.1417064973324486e+75
6.838905090738893e+57 2.1417064973324486e+75
1.958467639122848e+72 2.1417064973324486e+75
2.3310825477049833e+61 2.1417064973324486e+75
2.054281877055441e+62 2.1417064973324486e+75
1.3625995811979012e+66 2.1417064973324486e+75
6.3

2.644063758533077e+55 1.808218529958734e+79
6.100549995703837e+60 1.808218529958734e+79
5.951227231887348e+77 1.808218529958734e+79
1.675913721968547e+58 1.808218529958734e+79
1.383816971819906e+77 1.808218529958734e+79
1.739056572542664e+79 1.808218529958734e+79
2.828624748642959e+57 1.808218529958734e+79
8.564770381442755e+76 1.808218529958734e+79
6.327932048755836e+52 1.808218529958734e+79
3.758895861886897e+53 1.808218529958734e+79
2.0421380174718482e+58 1.808218529958734e+79
5.819134208191021e+77 1.808218529958734e+79
1.2374079737168238e+58 1.808218529958734e+79
2.4058449527171232e+76 1.808218529958734e+79
1.7970197432715155e+79 1.808218529958734e+79
7.808227515759865e+60 1.808218529958734e+79
2.2817135305899694e+75 1.808218529958734e+79
6.284955007784652e+53 1.808218529958734e+79
9.973294513833318e+57 1.808218529958734e+79
5.2291573660632896e+57 1.808218529958734e+79
1.0958934231588608e+77 1.808218529958734e+79
6.2253079712512464e+60 1.808218529958734e+79
1.1681102571270792e+74 1

7.702516681785694e+79 2.2262458164787522e+81
1.931368805418304e+64 2.2262458164787522e+81
1.921878030092471e+81 2.2262458164787522e+81
1.137276216163804e+79 2.226245816478752e+81
2.9990068659887896e+57 2.226245816478752e+81
1.2785617555661479e+80 2.226245816478752e+81
2.347433661520619e+52 2.226245816478752e+81
4.780574098274222e+60 2.226245816478752e+81
1.9310788106358517e+64 2.226245816478752e+81
1.9566748122271814e+79 2.226245816478752e+81
4.2806479305183434e+61 2.226245816478752e+81
2.067450130638227e+81 2.226245816478752e+81
3.084300146830197e+79 2.226245816478752e+81
2.8783381847813335e+52 2.226245816478752e+81
9.65088156078912e+76 2.226245816478752e+81
2.078516828865644e+53 2.226245816478752e+81
1.4980073793273995e+56 2.226245816478752e+81
4.7589902401734033e+61 2.226245816478752e+81
2.1325902969382135e+81 2.226245816478752e+81
1.6510946335071606e+58 2.226245816478752e+81
6.271600925662827e+79 2.226245816478752e+81
2.1492749203660394e+81 2.2262458164787514e+81
7.265945951926664e

4.191635376900823e+55 3.869990677228879e+82
1.9375039847030096e+79 3.869990677228879e+82
3.85142778773108e+82 3.8699906772288784e+82
1.560401302750397e+55 3.8699906772288784e+82
3.5033160806153522e+78 3.8699906772288784e+82
1.5752779955668838e+45 3.8699906772288784e+82
2.455241956000482e+55 3.8699906772288784e+82
1.7370323851388095e+55 3.8699906772288784e+82
1.819679753236405e+80 3.8699906772288784e+82
4.4626631379632285e+58 3.8699906772288784e+82
1.5760357372942578e+77 3.8699906772288784e+82
3.8321464927280796e+82 3.869990677228878e+82
2.0375154946689215e+55 3.869990677228878e+82
3.7478092535363497e+80 3.869990677228878e+82
3.703628519415007e+46 3.869990677228878e+82
7.575456045849267e+56 3.869990677228878e+82
4.3909242207597837e+58 3.869990677228878e+82
3.349051692172558e+78 3.869990677228878e+82
1.077867224548548e+57 3.869990677228878e+82
3.1186796217222045e+77 3.869990677228878e+82
4.1028817666488483e+80 3.8699906772288784e+82
1.6776800569983358e+53 3.8699906772288784e+82
3.7914525

1.3713860578557626e+42 1.2317941002613984e+83
8.543658738148129e+54 1.2317941002613984e+83
2.156956200873551e+59 1.2317941002613984e+83
2.1758069328897283e+79 1.2317941002613984e+83
1.672099224721547e+57 1.2317941002613984e+83
4.402321703907837e+81 1.2317941002613984e+83
1.5872227486333157e+80 1.2317941002613984e+83
3.761164021274036e+50 1.2317941002613984e+83
5.212056306530228e+81 1.2317941002613984e+83
6.89930566386791e+39 1.2317941002613984e+83
6.548571982805014e+51 1.2317941002613984e+83
1.6807195307256925e+57 1.2317941002613984e+83
3.747345952333823e+80 1.2317941002613984e+83
4.3875546055918854e+57 1.2317941002613984e+83
1.174338968495129e+83 1.2317941002613984e+83
3.315825065716282e+80 1.2317941002613986e+83
1.1201274511543964e+55 1.2317941002613986e+83
2.0187436352508581e+80 1.2317941002613986e+83
2.4310984715014754e+41 1.2317941002613986e+83
3.289540263840541e+57 1.2317941002613986e+83
1.0980212664397298e+57 1.2317941002613986e+83
1.8009264020951025e+82 1.2317941002613986e+83
3

1.2397206222885387e+78 8.188803175470889e+83
1.6299152236035316e+53 8.188803175470889e+83
5.639243134772485e+81 8.188803175470889e+83
3.572388911552353e+80 8.18880317547089e+83
9.464317885570958e+49 8.18880317547089e+83
1.351096340854932e+81 8.18880317547089e+83
3.380865941806975e+32 8.18880317547089e+83
1.6725260420208888e+52 8.18880317547089e+83
1.4627200050255325e+53 8.18880317547089e+83
2.197349753833356e+82 8.18880317547089e+83
1.974388224647462e+60 8.18880317547089e+83
7.951984847767452e+83 8.18880317547089e+83
1.3805775061295686e+81 8.188803175470889e+83
2.1696012580203603e+48 8.188803175470889e+83
2.0950158923359234e+82 8.188803175470889e+83
1.1371740817463199e+39 8.188803175470889e+83
3.3370324949944417e+56 8.188803175470889e+83
1.974054538217866e+60 8.188803175470889e+83
5.448247380273069e+81 8.188803175470889e+83
2.903880405268284e+57 8.188803175470889e+83
7.91101333737327e+83 8.188803175470889e+83
6.814263225014857e+81 8.188803175470887e+83
1.7991557314052682e+43 8.18880317

5.506198026602995e+81 2.3508701802910176e+84
7.030537971175467e+78 2.3508701802910184e+84
5.427912635321415e+44 2.3508701802910184e+84
1.3004901542555252e+82 2.3508701802910184e+84
2.0012497509091027e+26 2.3508701802910184e+84
3.94888944930088e+51 2.3508701802910184e+84
1.6673404691043842e+54 2.3508701802910184e+84
1.3189897021795213e+80 2.3508701802910184e+84
2.6313148439545922e+56 2.3508701802910184e+84
2.337726349240274e+84 2.3508701802910184e+84
5.208265751984709e+75 2.350870180291019e+84
4.168005798667025e+41 2.350870180291019e+84
1.389242999233756e+80 2.350870180291019e+84
2.1898573838738975e+27 2.350870180291019e+84
4.4789932149607353e+52 2.350870180291019e+84
2.630906433533017e+56 2.350870180291019e+84
9.197767854350655e+78 2.350870180291019e+84
1.9019747306204968e+55 2.350870180291019e+84
2.3507220530149752e+84 2.350870180291019e+84
8.100672865846947e+76 2.350870180291019e+84
9.046326416891053e+39 2.350870180291019e+84
9.121969391444167e+78 2.350870180291019e+84
3.758632135440

5.086097927002889e+84 5.189626577121813e+84
1.17052353524331e+41 5.189626577121813e+84
7.162641690878131e+82 5.189626577121813e+84
1.9725137440601704e+27 5.189626577121813e+84
2.0328835453887137e+52 5.189626577121813e+84
5.8349003428098675e+54 5.189626577121813e+84
2.8103113101301523e+82 5.189626577121813e+84
1.2937973907295755e+51 5.189626577121813e+84
3.799120108840436e+81 5.189626577121813e+84
1.9570903344886676e+81 5.1896265771218115e+84
2.5293025560733608e+42 5.1896265771218115e+84
5.112243949769701e+84 5.1896265771218115e+84
3.936634886223946e+19 5.1896265771218115e+84
2.2783061252923093e+49 5.1896265771218115e+84
2.1599849783480843e+52 5.1896265771218115e+84
3.0078786404050897e+78 5.1896265771218115e+84
7.776185779557589e+51 5.1896265771218115e+84
7.542252913898135e+82 5.1896265771218115e+84
2.7373646039246085e+79 5.189626577121812e+84
5.787757233696096e+39 5.189626577121812e+84
1.932724567089827e+81 5.189626577121812e+84
5.2252986955745735e+20 5.189626577121812e+84
4.9475000872

6.474619517633506e+74 9.02585403865448e+84
1.4654029319973162e+72 9.02585403865448e+84
1.4167768690602887e+50 9.02585403865448e+84
5.3044302912385707e+70 9.02585403865448e+84
1.41996941778055e+72 9.02585403865448e+84
1.515890379265459e+33 9.02585403865448e+84
4.543351421676657e+70 9.02585403865448e+84
8.670862223882494e+45 9.02585403865448e+84
9.02585089573668e+84 9.02585403865448e+84
3.142268821005719e+78 9.02585403865448e+84
4.951909017955424e+74 9.02585403865448e+84
8.383050463378929e+49 9.02585403865448e+84
1.523240942707206e+74 9.02585403865448e+84
1.942328086725742e+74 9.025854038654486e+84
1.2586658809965582e+33 9.025854038654486e+84
3.023780625407487e+74 9.025854038654486e+84
1.4244689868086541e+48 9.025854038654486e+84
9.000734090408734e+84 9.025854038654486e+84
2.5116805327947672e+82 9.025854038654486e+84
1.9681083320175637e+77 9.025854038654486e+84
2.022448574869e+50 9.025854038654486e+84
2.9456103573317474e+78 9.025854038654486e+84
1.882267275513421e+75 9.025854038654482e+8

1.7916125832981192e+82 1.1918810200508912e+85
4.2044123153797016e+46 1.1918810200508912e+85
1.1898672149484842e+85 1.1918810200508912e+85
1.6363030159772908e+82 1.1918810200508912e+85
9.157558921268234e+27 1.1918810200508912e+85
1.5848312682818545e+81 1.1918810200508912e+85
7.990804476735971e+32 1.1918810200508912e+85
1.1863784946045126e+66 1.1918810200508912e+85
5.530332220395483e+70 1.1918810200508912e+85
6.159703345555808e+84 1.1918810200508912e+85
4.5567376014631274e+46 1.1918810200508912e+85
5.741158993524993e+84 1.1918810200508912e+85
6.165855857551632e+84 1.191881020050891e+85
1.5101568504828593e+30 1.191881020050891e+85
1.0210518163948547e+82 1.191881020050891e+85
1.002049163544945e+30 1.191881020050891e+85
6.510802022995802e+62 1.191881020050891e+85
1.1857274144022128e+66 1.191881020050891e+85
5.652663891765627e+84 1.191881020050891e+85
1.8300379050572681e+46 1.191881020050891e+85
9.00799330277027e+82 1.191881020050891e+85
1.171169648712338e+85 1.191881020050891e+85
1.65974599

2.4883855017519074e+79 1.2973380876893426e+85
1.2939150037581812e+85 1.2973380876893427e+85
9.891811408334544e+27 1.2973380876893427e+85
3.3640627614391313e+82 1.2973380876893427e+85
27594990897.670025 1.2973380876893427e+85
1.7271655498216035e+50 1.2973380876893427e+85
3.5237203287867506e+51 1.2973380876893427e+85
5.757882046876434e+80 1.2973380876893427e+85
5.030289997684857e+41 1.2973380876893427e+85
1.4423492535750773e+79 1.2973380876893427e+85
2.360945023455279e+82 1.2973380876893427e+85
1.1810289078824838e+26 1.2973380876893427e+85
1.2916116375551948e+85 1.2973380876893427e+85
6427.978198394779 1.2973380876893427e+85
2.632586692085547e+44 1.2973380876893427e+85
1.7271629222652012e+50 1.2973380876893427e+85
6.383699935652747e+78 1.2973380876893427e+85
3.6492809387306615e+40 1.2973380876893427e+85
3.36486674069914e+82 1.2973380876893427e+85
5.0327472638662565e+81 1.2973380876893426e+85
1.3437198073093134e+28 1.2973380876893426e+85
1.8583086670622183e+82 1.2973380876893426e+85
1.295

4.8401998226352006e+23 1.329921087491629e+85
9.328140554348962e+81 1.329921087491629e+85
4.473119560209952e-08 1.329921087491629e+85
4.422108266015655e+37 1.329921087491629e+85
1.1154229793434381e+38 1.329921087491629e+85
2.481355636810414e+83 1.329921087491629e+85
9.248984813371696e+41 1.329921087491629e+85
1.712650857053499e+81 1.329921087491629e+85
6.193222637283608e+82 1.329921087491629e+85
1.022174707311525e+25 1.329921087491629e+85
1.322623785713205e+85 1.329921087491629e+85
1.2351666086315103e-09 1.329921087491629e+85
5.429605735110253e+39 1.329921087491629e+85
9.195130966847193e+41 1.329921087491629e+85
5.355578274380573e+78 1.329921087491629e+85
8.876368259240518e+40 1.329921087491629e+85
1.1035435833128082e+82 1.329921087491629e+85
4.1536310102836735e+79 1.3299210874916288e+85
1.883028482112518e+22 1.3299210874916288e+85
6.189604564100761e+82 1.3299210874916288e+85
1.8091055808311124e-11 1.3299210874916288e+85
2.1843750314783537e+38 1.3299210874916288e+85
9.39748508243676e+40

2.3397814811078155e-17 1.3666936644590887e+85
7.76897122468641e+32 1.3666936644590887e+85
2.1401800206078364e+39 1.3666936644590887e+85
3.917238299099561e+81 1.3666936644590887e+85
1.2813186135615578e+37 1.3666936644590887e+85
1.365004610096633e+85 1.3666936644590887e+85
3.951025268230924e+81 1.3666936644590884e+85
1.0202721615499436e+16 1.3666936644590884e+85
2.0885896225186212e+78 1.3666936644590884e+85
3.49815832562412e-14 1.3666936644590884e+85
8.123578542418327e+36 1.3666936644590884e+85
4.690384490319721e+36 1.3666936644590884e+85
1.359354813215932e+85 1.3666936644590884e+85
3.109780106531098e+41 1.3666936644590884e+85
6.943539857371061e+82 1.3666936644590884e+85
1.3439464751298128e+85 1.3666936644590887e+85
1.7105349832642368e+18 1.3666936644590887e+85
1.5803440612942593e+83 1.3666936644590887e+85
1.0386810995443874e-10 1.3666936644590887e+85
1.1888687442324058e+39 1.3666936644590887e+85
3.097972654874198e+41 1.3666936644590887e+85
6.23526571210335e+82 1.3666936644590887e+85
7.0

5.2659264059979124e+32 1.5847131924007666e+85
4.516149548148564e+38 1.5847131924007666e+85
5.205563361742914e+80 1.5847131924007666e+85
8.898532407471806e+34 1.5847131924007666e+85
1.5823605546749394e+85 1.5847131924007666e+85
8.566709410486918e+78 1.584713192400767e+85
397462610624.4623 1.584713192400767e+85
5.193140602632433e+80 1.584713192400767e+85
7.285821987681788e-26 1.584713192400767e+85
1.1246264423309484e+33 1.584713192400767e+85
8.838729027298689e+34 1.584713192400767e+85
2.6956806615733154e+82 1.584713192400767e+85
9.70782040467769e+38 1.584713192400767e+85
1.5819647236622262e+85 1.584713192400767e+85
3.3959008432747406e+81 1.5847131924007666e+85
5023734591.496528 1.5847131924007666e+85
2.35694724818689e+82 1.5847131924007666e+85
6.989250684709123e-21 1.5847131924007666e+85
3.439931490090515e+33 1.5847131924007666e+85
9.707797251627211e+38 1.5847131924007666e+85
2.3199993921744743e+83 1.5847131924007666e+85
2.6639778064283415e+35 1.5847131924007666e+85
1.5588166611465076e+8

8.486284243342416e+82 3.0043179065028982e+85
8.13996983558237e+76 3.0043179065028975e+85
127.09205055780845 3.0043179065028975e+85
4.3449774503848306e+79 3.0043179065028975e+85
2573349226738460.5 3.0043179065028975e+85
7.28679385535944e+75 3.0043179065028975e+85
3.1586780535868346e+81 3.0043179065028975e+85
5.7905448313777665e+81 3.0043179065028975e+85
5.935082162668891e+32 3.0043179065028975e+85
3.0034186303683015e+85 3.0043179065028975e+85
1.1921449583007688e+80 3.0043179065028975e+85
45368.927375609506 3.0043179065028975e+85
5.671411735246045e+81 3.0043179065028975e+85
66608511515.02796 3.0043179065028975e+85
4.597284050252434e+70 3.0043179065028975e+85
7.286747882518939e+75 3.0043179065028975e+85
6.483803989241014e+82 3.0043179065028975e+85
1.6198359689132484e+33 3.0043179065028975e+85
2.9972550391618696e+85 3.0043179065028975e+85
6.24489577605865e+82 3.0043179065028975e+85
60783.127274479564 3.0043179065028975e+85
2.5082966276537416e+81 3.0043179065028975e+85
497734144.933484 3.00

20.321156581306415 6.402443306756146e+85
1.2338427668465914e+83 6.402443306756146e+85
3.154222713315046e-09 6.402443306756146e+85
2.16342277856934e+52 6.402443306756146e+85
3.4743344734073414e+57 6.402443306756146e+85
4.225341226520927e+83 6.402443306756146e+85
6.736513378318416e+26 6.402443306756146e+85
8.041944338521444e+81 6.402443306756146e+85
6.388917007372079e+85 6.402443306756145e+85
35892.933710010875 6.402443306756145e+85
3.836772817481414e+81 6.402443306756145e+85
4.696689239796436e-13 6.402443306756145e+85
5.6525692277483116e+51 6.402443306756145e+85
1.5981658557945084e+52 6.402443306756145e+85
1.3134899267007157e+83 6.402443306756145e+85
3.674558424109314e+29 6.402443306756145e+85
7.722835310900511e+79 6.402443306756145e+85
6.389141217194416e+85 6.402443306756144e+85
214372.52186949312 6.402443306756144e+85
1.291068944466897e+83 6.402443306756144e+85
4.645212583030944e-15 6.402443306756144e+85
3.3389089593526475e+50 6.402443306756144e+85
5.3186783318130475e+51 6.40244330675

3.5450952370963723e-32 9.000318679207253e+85
2.3172978049244183e+39 9.000318679207253e+85
6.150964682349128e+43 9.000318679207253e+85
1.0054021701275239e+84 9.000318679207253e+85
6.189546426924421e+28 9.000318679207253e+85
8.703718438194882e+85 9.000318679207253e+85
1.2051371304664394e+84 9.000318679207251e+85
4.735052167946472e-07 9.000318679207251e+85
4.561640997344114e+80 9.000318679207251e+85
3.102771948919587e-32 9.000318679207251e+85
4.381166139485375e+33 9.000318679207251e+85
2.3172934238201742e+39 9.000318679207251e+85
8.846793312725685e+85 9.000318679207251e+85
1.1764969620703406e+25 9.000318679207251e+85
3.296603702494933e+83 9.000318679207251e+85
8.962882642387733e+85 9.000318679207253e+85
14.91541174542028 9.000318679207253e+85
4.4243833845962536e+82 9.000318679207253e+85
2.7869381334092165e-38 9.000318679207253e+85
1.6667345190680952e+33 9.000318679207253e+85
2.7144316321822496e+33 9.000318679207253e+85
3.2852005554998546e+83 9.000318679207253e+85
1.8504018444892017e+28 9.

2.3993144471631762e+24 1.0265756800750858e+86
1.944790864924325e+28 1.0265756800750858e+86
2.2335807923393925e+80 1.0265756800750858e+86
3.217208103130658e+26 1.0265756800750858e+86
1.0265166477479735e+86 1.0265756800750858e+86
1.7659953864102812e+78 1.0265756800750858e+86
1.3162710942139808e-10 1.0265756800750858e+86
2.2171401618795427e+80 1.0265756800750858e+86
3.5069044346506154e-56 1.0265756800750858e+86
1.697855654403669e+22 1.0265756800750858e+86
3.241031462036849e+26 1.0265756800750858e+86
8.280988032507708e+82 1.0265756800750858e+86
1.3650732849502661e+26 1.0265756800750858e+86
1.0257453464717193e+86 1.0265756800750858e+86
2.0202010440991855e+80 1.0265756800750861e+86
1.988541123825426e-10 1.0265756800750861e+86
8.260962621605358e+82 1.0265756800750861e+86
4.535426062402573e-57 1.0265756800750861e+86
2.8998740226666357e+19 1.0265756800750861e+86
1.3652427805283043e+26 1.0265756800750861e+86
2.5418094051706228e+82 1.0265756800750861e+86
5.533513818781214e+23 1.0265756800750861e+

1.7217716422986318e+79 1.0769483265492284e+86
1.9156486881579645e+22 1.0769483265492284e+86
3.9897477920594465e+83 1.0769483265492284e+86
7.079394946958998e+80 1.0769483265492286e+86
6.385377939032638e-11 1.0769483265492286e+86
4.50115036008764e+82 1.0769483265492286e+86
1.0792636885380047e-65 1.0769483265492286e+86
1.1730754060869291e+20 1.0769483265492286e+86
1.9237656222326447e+22 1.0769483265492286e+86
1.7119161996415e+83 1.0769483265492286e+86
2.2126483342756583e+25 1.0769483265492286e+86
1.0747792159186313e+86 1.0769483265492286e+86
6.033155947994023e+79 1.0769483265492286e+86
4.846520489522681e-14 1.0769483265492286e+86
1.7183922789936594e+83 1.0769483265492286e+86
2.7710170304819866e-64 1.0769483265492286e+86
2.682455925471885e+19 1.0769483265492286e+86
2.212657382573793e+25 1.0769483265492286e+86
3.822949149989448e+81 1.0769483265492286e+86
4.4007170991614984e+21 1.0769483265492286e+86
1.0751911014631402e+86 1.0769483265492286e+86
6.607273303319294e+79 1.0769483265492287e+86
1

4.442886227430591e-18 1.0955002250973104e+86
2.6214048912824947e+75 1.0955002250973104e+86
1.313730895863739e-08 1.0955002250973104e+86
1.0924312060789683e+86 1.0955002250973104e+86
3.068486595950304e+83 1.0955002250973104e+86
2.3718252904074695e+78 1.0955002250973104e+86
8.096223338924499e+20 1.0955002250973104e+86
5.086658516231143e+79 1.0955002250973104e+86
8.16137354080998e+75 1.0955002250973105e+86
8.33890333194061e-22 1.0955002250973105e+86
2.364871228795951e+78 1.0955002250973105e+86
3.5044065667823404e-08 1.0955002250973105e+86
8.090999100495439e+81 1.0955002250973105e+86
1.0923502960879635e+86 1.0955002250973105e+86
1.0719264581407947e+80 1.0955002250973105e+86
1.0159322770817298e+18 1.0955002250973105e+86
3.067923361557835e+83 1.0955002250973105e+86
2.125053260610026e+77 1.0955002250973106e+86
1.0635110742453935e-21 1.0955002250973106e+86
1.0698830186155927e+80 1.0955002250973106e+86
1.493934537865151e-12 1.0955002250973106e+86
1.6894515775045585e+76 1.0955002250973106e+86
8.

5.12193629395331e-28 1.1021998344360642e+86
1.2870596042457845e+63 1.1021998344360642e+86
9.386778029126294e+65 1.1021998344360642e+86
1.0183689694365243e+85 1.1021998344360642e+86
3611439747072197.5 1.1021998344360642e+86
4.453583632344646e+82 1.1021998344360642e+86
1.094830412611453e+86 1.1021998344360642e+86
1.5797846874305083e-22 1.1021998344360642e+86
6.48157937794796e+83 1.1021998344360642e+86
5.25178430786783e-32 1.1021998344360642e+86
3.2248738786850076e+57 1.1021998344360642e+86
1.2870563793719058e+63 1.1021998344360642e+86
8.387894302542392e+82 1.1021998344360642e+86
726891401004.151 1.1021998344360642e+86
4.905301640899496e+81 1.1021998344360642e+86
1.094269348323581e+86 1.1021998344360644e+86
1.3613833917639373e-22 1.1021998344360644e+86
1.3998537181264828e+83 1.1021998344360644e+86
6.089663183022948e-37 1.1021998344360644e+86
3.224068739183697e+52 1.1021998344360644e+86
3.2248416379976154e+57 1.1021998344360644e+86
6.449135937034571e+83 1.1021998344360644e+86
4818626669914

7.69205069973118e+44 1.1046229865982261e+86
4.6870111296183856e+50 1.1046229865982261e+86
4.1699745826980126e+79 1.1046229865982261e+86
29083785542.26672 1.1046229865982261e+86
2.2659217981885345e+83 1.1046229865982261e+86
3.47185841353783e+82 1.104622986598226e+86
3.1981980843909095e-23 1.104622986598226e+86
1.6536252897695256e+83 1.104622986598226e+86
9.228363013586346e-59 1.104622986598226e+86
6.824631701410089e+43 1.104622986598226e+86
7.009587529590171e+44 1.104622986598226e+86
2.2946913844898783e+84 1.104622986598226e+86
8.221286244021025e+17 1.104622986598226e+86
1.0796752616222039e+86 1.104622986598226e+86
2.3634139542624415e+83 1.104622986598226e+86
1.2924500735282194e-25 1.104622986598226e+86
2.0930685731990123e+84 1.104622986598226e+86
4.83202713315509e-60 1.104622986598226e+86
2.121360806758017e+39 1.104622986598226e+86
6.824419565329413e+43 1.104622986598226e+86
1.2220370183822364e+84 1.104622986598226e+86
259914479121794.4 1.104622986598226e+86
1.0691085167281511e+86 1.10

1.9107446658984334e+79 1.105507215218301e+86
25880188584.42258 1.105507215218301e+86
5.792170900187077e+82 1.105507215218301e+86
1.9005710703744477e+80 1.1055072152183007e+86
2.7404007145132495e-29 1.1055072152183007e+86
3.587354260213325e+83 1.1055072152183007e+86
6.882174092695156e-81 1.1055072152183007e+86
1.5038845727072157e+28 1.1055072152183007e+86
7.984210785306812e+30 1.1055072152183007e+86
5.9093110593712765e+81 1.1055072152183007e+86
21463260885608.21 1.1055072152183007e+86
1.1018588672764232e+86 1.1055072152183007e+86
1.2904526799103197e+77 1.1055072152183007e+86
3.037023729603444e-32 1.1055072152183007e+86
6.09923912114073e+81 1.1055072152183007e+86
5.176204459531913e-85 1.1055072152183007e+86
1.8461900927354604e+24 1.1055072152183007e+86
1.5036999536979445e+28 1.1055072152183007e+86
2.3675771808315397e+80 1.1055072152183007e+86
1403586370218.3655 1.1055072152183007e+86
1.1054438539594557e+86 1.1055072152183007e+86
1.87281095641216e+78 1.1055072152183004e+86
4.9748024476172

7.528036374439181e+83 1.1058333660178559e+86
1.0944885807870347e+86 1.105833366017856e+86
4.158984227341395e-33 1.105833366017856e+86
3.8165581697386376e+83 1.105833366017856e+86
6.962569323823061e-99 1.105833366017856e+86
75712218144.00354 1.105833366017856e+86
5752319541067.794 1.105833366017856e+86
7.277532117217622e+83 1.105833366017856e+86
45119945.23279509 1.105833366017856e+86
2.506949438650684e+82 1.105833366017856e+86
4.6612919315719715e+82 1.1058333660178558e+86
1.2957058939758642e-31 1.1058333660178558e+86
1.1012999837110949e+86 1.1058333660178558e+86
1.3514371166958844e-106 1.1058333660178558e+86
107501957.56827731 1.1058333660178558e+86
75649836131.66806 1.1058333660178558e+86
1.742538854986264e+79 1.1058333660178558e+86
79029820.65774012 1.1058333660178558e+86
4.067078859718206e+83 1.1058333660178558e+86
7.23724752393227e+80 1.1058333660178562e+86
2.3186125445982908e-34 1.1058333660178562e+86
4.590661995187635e+82 1.1058333660178562e+86
1.2336636980477464e-107 1.105833366

In [13]:
print ("Pi", gmmhmm.pi)
print ("A", gmmhmm.A)
print ("weights", gmmhmm.w)
print ("means", gmmhmm.means)
print ("covars", gmmhmm.covars )

Pi [0. 1. 0.]
A [[7.46221928e-001 3.79464330e-117 2.53778072e-001]
 [3.99997840e-117 7.99890798e-001 2.00109202e-001]
 [2.29378959e-001 1.53164733e-074 7.70621041e-001]]
weights [[0.42821204 0.57178796]
 [0.59978264 0.40021736]
 [0.36854573 0.63145427]]
means [[[-0.01852892 -0.0311536  -0.15865663  0.08787462 -0.08240256
   -0.09336579 -0.02068232 -0.08570082]
  [ 0.0713058   0.04279161 -0.01695202  0.07253809 -0.11164556
    0.08556417 -0.03006398  0.01603204]]

 [[-0.11526557 -0.00076141 -0.13871864 -0.13188004  0.12327444
    0.06783556  0.00323332 -0.19238918]
  [ 0.01921302  0.07024631 -0.08021395 -0.00456197 -0.0277012
   -0.07167978  0.11054558  0.23225296]]

 [[-0.11367889 -0.12929565  0.11472593 -0.11701811 -0.10900228
    0.05515793  0.15573707  0.01630697]
  [ 0.04486602  0.03039108  0.04573143 -0.02970068  0.09157236
   -0.05298621  0.04798535 -0.12756416]]]
covars [[matrix([[ 0.05172096, -0.01331339,  0.00715527, -0.00345719,  0.0065036 ,
         -0.0061864 ,  0.00816626,