In [1]:
from hmm.continuous.GMHMM import GMHMM
from hmm.discrete.DiscreteHMM import DiscreteHMM
import numpy as np

Model attributes:
   - n            : number of hidden states
   - m            : number of mixtures in each state (each 'symbol' like in the discrete case points to a mixture)
   - d            : number of features (an observation can contain multiple features)
   - A            : hidden states transition probability matrix ([NxN] numpy array)
   - means        : means of the different mixtures ([NxMxD] numpy array)
   - covars       : covars of the different mixtures ([NxM] array of [DxD] covar matrices)
   - w            : weighing of each state's mixture components ([NxM] numpy array)
   - pi           : initial state's PMF ([N] numpy array).

In [2]:
N = 5 # number of hidden states
M = 4 # number of mixtures in each state
D = 2 # number of features (a observation can contain multiple features)

In [4]:
atmp = np.random.random_sample((N, N))
row_sums = atmp.sum(axis=1)
A = np.array(atmp / row_sums[:, np.newaxis], dtype=np.double)
print("Transition Matrix A [NxN]")
print(A)

Transition Matrix A [NxN]
[[0.38055872 0.15927289 0.12462602 0.16143003 0.17411234]
 [0.25548645 0.28316931 0.00119979 0.26341321 0.19673124]
 [0.30025526 0.06599526 0.04790385 0.36833476 0.21751088]
 [0.33796575 0.35701067 0.01897527 0.10028393 0.18576438]
 [0.13862223 0.43333641 0.21601035 0.02233762 0.18969339]]


In [5]:
wtmp = np.random.random_sample((N, M))
row_sums = wtmp.sum(axis=1)
w = np.array(wtmp / row_sums[:, np.newaxis], dtype=np.double)
print("Weight of each state's mixture components [NxM]")
print(w)

Weight of each state's mixture components [NxM]
[[0.35872207 0.37179468 0.02067748 0.24880577]
 [0.61782712 0.25972863 0.04587088 0.07657337]
 [0.19716574 0.47988399 0.08669536 0.23625491]
 [0.45927324 0.04540421 0.30067305 0.19464951]
 [0.43288784 0.08670828 0.39508369 0.0853202 ]]


In [6]:
means = np.array((0.6 * np.random.random_sample((N, M, D)) - 0.3), dtype=np.double)
print("Means of the different mixtures [NxMxD]")
print(means)

Means of the different mixtures [NxMxD]
[[[ 0.02134323  0.04263977]
  [-0.20614765 -0.09773459]
  [-0.24270881 -0.220104  ]
  [ 0.15540907  0.03027637]]

 [[ 0.03938439 -0.08310588]
  [ 0.11461906 -0.19714286]
  [ 0.29634035 -0.18669578]
  [-0.24842522  0.03906607]]

 [[ 0.06914688 -0.16093834]
  [ 0.19297982 -0.11721102]
  [ 0.01735768 -0.14250086]
  [ 0.23359579 -0.17218666]]

 [[-0.04482052 -0.12365444]
  [ 0.03405649  0.14317221]
  [ 0.16455883  0.16537114]
  [-0.20947983  0.25575957]]

 [[ 0.03285289  0.18923295]
  [-0.24077243 -0.0948618 ]
  [ 0.00423223 -0.22171985]
  [-0.26077704 -0.29293943]]]


In [9]:
covars = np.zeros((N,M,D,D))

for i in range(N):
    for j in range(M):
        for k in range(D):
            covars[i][j][k][k] = 1
print("Covars of the different mixtures ([NxM] array of [DxD] covar matrices)")            
print(covars)

Covars of the different mixtures ([NxM] array of [DxD] covar matrices)
[[[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]


 [[[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]

  [[1. 0.]
   [0. 1.]]]]


In [12]:
pitmp = np.random.random_sample((N))
pi = np.array(pitmp / sum(pitmp), dtype=np.double)
print("initial state")
print(pi)

initial state
[0.3459891  0.26348043 0.09045033 0.09667524 0.20340491]


In [14]:
# initialization
gmmhmm = GMHMM(N, M, D, A, means, covars, w, pi, init_type='user', verbose=True)
print(gmmhmm)

In [17]:
# observation matrix
obs = np.array((0.6 * np.random.random_sample((40, D)) - 0.3), dtype=np.double)
print(obs.shape)

(40, 2)


In [18]:
print ("Doing Baum-welch")
gmmhmm.train(obs,1000)

Doing Baum-welch
iter:  0 , L(model|O) = -75.43719114059516 , L(model_new|O) = 22.606341028175237 , converging = True
iter:  1 , L(model|O) = 22.606341028175237 , L(model_new|O) = 28.22706458615942 , converging = True
iter:  2 , L(model|O) = 28.22706458615942 , L(model_new|O) = 28.222077699586258 , converging = False
iter:  3 , L(model|O) = 28.222077699586258 , L(model_new|O) = 28.220644752256007 , converging = False
iter:  4 , L(model|O) = 28.220644752256007 , L(model_new|O) = 28.22754746538727 , converging = True
iter:  5 , L(model|O) = 28.22754746538727 , L(model_new|O) = 28.24158517934619 , converging = True
iter:  6 , L(model|O) = 28.24158517934619 , L(model_new|O) = 28.2627585276684 , converging = True
iter:  7 , L(model|O) = 28.2627585276684 , L(model_new|O) = 28.29172077518208 , converging = True
iter:  8 , L(model|O) = 28.29172077518208 , L(model_new|O) = 28.329302027775324 , converging = True
iter:  9 , L(model|O) = 28.329302027775324 , L(model_new|O) = 28.376100900159148 , c

iter:  84 , L(model|O) = 37.278825455279545 , L(model_new|O) = 37.77006009805424 , converging = True
iter:  85 , L(model|O) = 37.77006009805424 , L(model_new|O) = 38.34150183970945 , converging = True
iter:  86 , L(model|O) = 38.34150183970945 , L(model_new|O) = 38.936942779698306 , converging = True
iter:  87 , L(model|O) = 38.936942779698306 , L(model_new|O) = 39.459213503064014 , converging = True
iter:  88 , L(model|O) = 39.459213503064014 , L(model_new|O) = 39.839362162768005 , converging = True
iter:  89 , L(model|O) = 39.839362162768005 , L(model_new|O) = 40.07608496951907 , converging = True
iter:  90 , L(model|O) = 40.07608496951907 , L(model_new|O) = 40.20785298461716 , converging = True
iter:  91 , L(model|O) = 40.20785298461716 , L(model_new|O) = 40.275494616716394 , converging = True
iter:  92 , L(model|O) = 40.275494616716394 , L(model_new|O) = 40.307571882088226 , converging = True
iter:  93 , L(model|O) = 40.307571882088226 , L(model_new|O) = 40.32090032454848 , converg

In [19]:
print ("Pi", gmmhmm.pi)
print ("A", gmmhmm.A)
print ("weights", gmmhmm.w)
print ("means", gmmhmm.means)
print ("covars", gmmhmm.covars)

Pi [1.00000000e+000 2.99790589e-079 6.75830440e-253 1.31168135e-174
 1.53253572e-134]
A [[5.73845987e-01 1.42214219e-32 4.26154013e-01 1.07174816e-23
  5.90089856e-29]
 [9.99999843e-01 4.81944948e-08 5.27028464e-26 4.08142173e-15
  1.08509305e-07]
 [4.14278763e-20 8.60396121e-29 3.10828536e-01 6.89171464e-01
  1.77838677e-19]
 [1.85448792e-26 1.47456917e-18 4.86619280e-12 7.76637951e-01
  2.23362049e-01]
 [2.82722823e-12 3.69942837e-01 8.99274924e-31 1.00179443e-13
  6.30057163e-01]]
weights [[0.38742164 0.3749456  0.01710525 0.22052752]
 [0.66725133 0.22937568 0.02996857 0.07340442]
 [0.23034284 0.45841751 0.11295213 0.19828752]
 [0.56152894 0.04452257 0.23455335 0.15939514]
 [0.41951683 0.09406589 0.41786152 0.06855577]]
means [[[-0.01928005  0.16584512]
  [-0.01928005  0.16584512]
  [-0.01928005  0.16584512]
  [-0.01928005  0.16584512]]

 [[ 0.0870531  -0.09404423]
  [ 0.0870531  -0.09404423]
  [ 0.0870531  -0.09404423]
  [ 0.0870531  -0.09404423]]

 [[-0.20669708  0.02131184]
  [-0